language: node_js
node_js:
  - "node"
notifications:
  email: false
cache:
  npm: true
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  overide:
    - npm ci
    - npm run:cy verify
install:
  - npm ci
  - npm run build
before_script:
  - npm start -- --silent &
script:
  - $(npm bin)/cypress run
